// --- CARDS / BLACKJACK ---
const suits=['♠','♥','♦','♣'],ranks=['2','3','4','5','6','7','8','9','10','J','Q','K','A'];
function freshDeck(decks=1){let d=[];for(let n=0;n<decks;n++)for(const s of suits)for(const r of ranks)d.push({r,s});return shuffle(d)}
function cardHtml(c,back=false){if(back)return `<div class="playing-card back"></div>`;const red=c.s==='♥'||c.s==='♦';return `<div class="playing-card ${red?'red':''}"><span class="corner">${c.r}${c.s}</span><span class="pip">${c.s}</span><span class="corner" style="align-self:flex-end;transform:rotate(180deg)">${c.r}${c.s}</span></div>`}
function blackjackValue(hand){let v=0,aces=0;for(const c of hand){if(c.r==='A'){v+=11;aces++}else if(['J','Q','K'].includes(c.r))v+=10;else v+=+c.r}while(v>21&&aces){v-=10;aces--}return {value:v,soft:aces>0}}
function renderBlackjack(){let shoe=freshDeck(6),player=[],dealer=[],stake=0,active=false;$('#gameMount').innerHTML=`<div class="casino-room room-blackjack"><div class="room-topline"><span class="rules-badge">6 DECKS · BLACKJACK 3:2 · DEALER HITS SOFT 17</span>${betControls('bjBet',100)}</div><div class="table-felt"><div class="table-label">DEALER <span id="dealerValue"></span></div><div class="hand-row" id="dealerHand"></div><div class="table-label">PLAYER <span id="playerValue"></span></div><div class="hand-row" id="playerHand"></div><div class="game-actions"><button class="primary-btn" id="dealBJ">DEAL</button><button class="secondary-btn" id="hitBJ" disabled>HIT</button><button class="secondary-btn" id="standBJ" disabled>STAND</button><button class="secondary-btn" id="doubleBJ" disabled>DOUBLE</button></div><div id="bjResult" class="result-banner">Place a simulated wager and deal.</div></div></div>`;wireQuickBets($('#gameMount'));const draw=()=>shoe.pop();
  function paint(hide=true){$('#playerHand').innerHTML=player.map(c=>cardHtml(c)).join('');$('#dealerHand').innerHTML=dealer.map((c,i)=>hide&&i===1?cardHtml(c,true):cardHtml(c)).join('');$('#playerValue').textContent=player.length?`· ${blackjackValue(player).value}`:'';$('#dealerValue').textContent=dealer.length?(hide?`· ${blackjackValue([dealer[0]]).value} + ?`:`· ${blackjackValue(dealer).value}`):''}
  function buttons(on){$('#hitBJ').disabled=!on;$('#standBJ').disabled=!on;$('#doubleBJ').disabled=!on;$('#dealBJ').disabled=on}
  function finish(type,text,ret=0){active=false;buttons(false);paint(false);if(ret)adjust(ret,{win:type==='win'});$('#bjResult').innerHTML=`<strong class="${type}">${text}</strong>`;if(type==='win'&&ret>=stake*2.5)confetti()}
  function dealerPlay(){while(true){const x=blackjackValue(dealer);if(x.value<17||(x.value===17&&x.soft))dealer.push(draw());else break}const p=blackjackValue(player).value,d=blackjackValue(dealer).value;if(d>21)finish('win',`Dealer busts · return ${money(stake*2)}`,stake*2);else if(d>p)finish('loss',`Dealer ${d} beats ${p} · lose ${money(stake)}`);else if(d<p)finish('win',`${p} beats dealer ${d} · return ${money(stake*2)}`,stake*2);else finish('push',`Push at ${p} · ${money(stake)} returned`,stake)}
  $('#dealBJ').onclick=()=>{stake=getBet('bjBet');if(!stake)return;if(shoe.length<75)shoe=freshDeck(6);adjust(-stake,{wager:true});recordGame('blackjack');player=[draw(),draw()];dealer=[draw(),draw()];active=true;paint(true);buttons(true);const p=blackjackValue(player).value,d=blackjackValue(dealer).value;if(p===21&&d===21)finish('push','Both have blackjack · push',stake);else if(p===21)finish('win',`Natural blackjack · return ${money(stake*2.5)}`,stake*2.5);else if(d===21)finish('loss','Dealer has blackjack')};
  $('#hitBJ').onclick=()=>{if(!active)return;player.push(draw());$('#doubleBJ').disabled=true;paint(true);if(blackjackValue(player).value>21)finish('loss',`Bust at ${blackjackValue(player).value} · lose ${money(stake)}`)};$('#standBJ').onclick=dealerPlay;$('#doubleBJ').onclick=()=>{if(!active)return;adjust(-stake,{wager:true});stake*=2;player.push(draw());paint(true);if(blackjackValue(player).value>21)finish('loss',`Bust after doubling · lose ${money(stake)}`);else dealerPlay()}}

// --- ROULETTE ---
const rouletteReds=new Set([1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]);
function renderRoulette(){state.rouletteBet=null;$('#gameMount').innerHTML=`<div class="casino-room room-roulette"><div class="room-topline"><span class="rules-badge">AMERICAN WHEEL · 38 EQUALLY LIKELY POCKETS</span>${betControls('rouletteStake',100)}</div><div class="roulette-stage"><div class="roulette-machine"><div class="roulette-pointer"></div><div class="roulette-wheel" id="rouletteWheel"><span class="roulette-ball"></span></div><div class="roulette-result" id="rouletteResult">—</div></div><div class="betting-board"><p class="kicker">PLACE BET</p><div class="selected-bet" id="selectedRouletteBet">No bet selected</div><div class="roulette-numbers">${['0','00',...Array.from({length:36},(_,i)=>String(i+1))].map(n=>`<button class="roulette-bet-btn ${n==='0'||n==='00'?'green':rouletteReds.has(+n)?'red':'black'}" data-rbet="n:${n}">${n}</button>`).join('')}</div><div class="outside-bets">${[['red','RED'],['black','BLACK'],['odd','ODD'],['even','EVEN'],['low','1–18'],['high','19–36'],['d1','1st 12'],['d2','2nd 12'],['d3','3rd 12']].map(([k,l])=>`<button class="roulette-bet-btn" data-rbet="${k}">${l}</button>`).join('')}</div><div class="game-actions"><button class="primary-btn" id="spinRoulette">SPIN WHEEL</button></div><div id="rouletteBanner" class="result-banner">Straight 35:1 · Dozens 2:1 · Even-money 1:1</div></div></div></div>`;wireQuickBets($('#gameMount'));$$('[data-rbet]').forEach(b=>b.onclick=()=>{$$('[data-rbet]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.rouletteBet=b.dataset.rbet;$('#selectedRouletteBet').textContent='Selected: '+b.textContent.trim()});
  $('#spinRoulette').onclick=()=>{if(!state.rouletteBet)return toast('Choose a roulette bet');const stake=getBet('rouletteStake');if(!stake)return;adjust(-stake,{wager:true});recordGame('roulette');const pockets=['0','00',...Array.from({length:36},(_,i)=>String(i+1))],result=pockets[randInt(38)],n=Number(result),type=state.rouletteBet;let won=false,profitMult=0;if(type.startsWith('n:')){won=type.slice(2)===result;profitMult=35}else if(!['0','00'].includes(result)){if(type==='red')won=rouletteReds.has(n);if(type==='black')won=!rouletteReds.has(n);if(type==='odd')won=n%2===1;if(type==='even')won=n%2===0;if(type==='low')won=n<=18;if(type==='high')won=n>=19;if(type==='d1')won=n<=12;if(type==='d2')won=n>=13&&n<=24;if(type==='d3')won=n>=25;profitMult=['d1','d2','d3'].includes(type)?2:1}const ret=won?stake*(profitMult+1):0;const wheel=$('#rouletteWheel');wheel.style.transform=`rotate(${1440+randInt(720)}deg)`;$('#spinRoulette').disabled=true;setTimeout(()=>{if(ret)adjust(ret,{win:true});const color=['0','00'].includes(result)?'GREEN':rouletteReds.has(n)?'RED':'BLACK';$('#rouletteResult').textContent=`${result} · ${color}`;$('#rouletteBanner').innerHTML=won?`<strong class="win">WIN · ${money(ret)} returned</strong>`:`<strong class="loss">LOSE · ${money(stake)}</strong>`;$('#spinRoulette').disabled=false;if(profitMult>=35&&won)confetti()},2400)}}

// --- SLOTS ---
function renderSlots(){const symbols=[{s:'🍒',w:31,p:3},{s:'🍋',w:25,p:4},{s:'🔔',w:18,p:6},{s:'BAR',w:13,p:9},{s:'7',w:8,p:18},{s:'◆',w:5,p:35}],total=symbols.reduce((a,x)=>a+x.w,0);const pick=()=>{let r=Math.random()*total;for(const x of symbols){r-=x.w;if(r<0)return x.s}return symbols[0].s};$('#gameMount').innerHTML=`<div class="casino-room room-slots"><div class="room-topline"><span class="rules-badge">WEIGHTED SYMBOL RNG · CENTER PAYLINE</span>${betControls('slotBet',25)}</div><div class="slot-cabinet"><div class="slot-marquee">ROYAL REELS</div><div class="reels">${Array.from({length:5},(_,i)=>`<div class="reel" id="reel${i}">7</div>`).join('')}</div><div class="slot-payline"></div><div class="slot-display" id="slotDisplay">INSERT FAKE CREDIT · PRESS SPIN</div><div class="game-actions"><button class="primary-btn" id="slotSpin">SPIN</button></div><div class="stat-line"><span>◆ Cherry 31%</span><span>◆ Lemon 25%</span><span>◆ Bell 18%</span><span>◆ BAR 13%</span><span>◆ 7 8%</span><span>◆ Diamond 5%</span></div></div></div>`;wireQuickBets($('#gameMount'));$('#slotSpin').onclick=()=>{const stake=getBet('slotBet');if(!stake)return;adjust(-stake,{wager:true});recordGame('slots');const reels=$$('.reel');reels.forEach(r=>r.classList.add('spin'));let ticks=0,iv=setInterval(()=>{reels.forEach(r=>r.textContent=pick());if(++ticks>15){clearInterval(iv);const out=reels.map(()=>pick());reels.forEach((r,i)=>{r.classList.remove('spin');r.textContent=out[i]});const counts={};out.forEach(s=>counts[s]=(counts[s]||0)+1);let best=0,label='';for(const x of symbols){const c=counts[x.s]||0;if(c>=3){const m=x.p*(c===3?1:c===4?3:8);if(m>best){best=m;label=x.s}}}const ret=stake*best;if(ret)adjust(ret,{win:true});$('#slotDisplay').textContent=ret?`${label} COMBINATION · RETURN ${money(ret)}`:`NO PAYLINE · -${money(stake)}`;if(ret>=stake*50)confetti()}},72)}}

// --- HORSE RACING ---
function weightedPick(probs){let r=Math.random(),acc=0;for(let i=0;i<probs.length;i++){acc+=probs[i];if(r<=acc)return i}return probs.length-1}
function renderHorses(){const names=['Midnight Ace','Golden Circuit','Velvet Thunder','Lucky Comet','Royal Static','Emerald Rush'];const ratings=names.map(()=>.7+Math.random()*.7),sum=ratings.reduce((a,b)=>a+b),probs=ratings.map(x=>x/sum),odds=probs.map(p=>Math.max(1.1,.90/p));state.horseBet=null;const silks=['#a53c45','#326aa3','#c79b2b','#7354a6','#258264','#d06e31'];$('#gameMount').innerHTML=`<div class="casino-room room-horses"><div class="room-topline"><span class="rules-badge">GENERATED FIELD · 10% SIMULATED TRACK TAKE</span>${betControls('horseStake',100)}</div><div class="racebook"><div class="odds-board"><div class="odds-head"><span>NO.</span><span>RUNNER</span><span>DECIMAL</span><span>MODEL CHANCE</span></div>${names.map((n,i)=>`<div class="horse-line" data-horse="${i}"><span class="horse-silk" style="background:${silks[i]}">${i+1}</span><span class="horse-name"><b>${n}</b><small>Rating ${ratings[i].toFixed(2)}</small></span><span class="odds-price">${odds[i].toFixed(2)}×</span><span class="chance">${(probs[i]*100).toFixed(1)}%</span></div>`).join('')}</div><div class="race-track-wrap"><div class="track-grandstand"></div>${names.map((n,i)=>`<div class="race-lane"><span class="lane-id">${i+1} · ${n}</span><span class="race-horse" id="horse${i}">🏇</span></div>`).join('')}<div class="finish-line"></div></div><div class="game-actions"><button class="primary-btn" id="runRace">START RACE</button></div><div id="raceResult" class="result-banner">Select one horse from the live odds board.</div></div></div>`;wireQuickBets($('#gameMount'));$$('.horse-line').forEach(x=>x.onclick=()=>{$$('.horse-line').forEach(y=>y.classList.remove('active'));x.classList.add('active');state.horseBet=+x.dataset.horse});$('#runRace').onclick=()=>{if(state.horseBet==null)return toast('Select a horse');const stake=getBet('horseStake');if(!stake)return;adjust(-stake,{wager:true});recordGame('horses');const winner=weightedPick(probs),scores=names.map((_,i)=>i===winner?1.03:.78+Math.random()*.2),positions=Array(6).fill(0);scores[winner]=1.08;const horses=names.map((_,i)=>$('#horse'+i));$('#runRace').disabled=true;$('#raceResult').textContent='And they’re off…';let tick=0,iv=setInterval(()=>{tick++;for(let i=0;i<6;i++){const target=Math.min(100,(tick/70)*100*scores[i]);const jitter=tick<62?(Math.random()-.48)*1.4:0;positions[i]=Math.max(positions[i],target+jitter);horses[i].style.left=`min(${Math.max(0,positions[i])}%, calc(100% - 67px))`}if(tick>=70){clearInterval(iv);horses[winner].style.left='calc(100% - 67px)';const ret=winner===state.horseBet?stake*odds[winner]:0;if(ret)adjust(ret,{win:true});$('#raceResult').innerHTML=`<b>${names[winner]}</b> wins · ${ret?`<strong class="win">your ticket returns ${money(ret)}</strong>`:`<strong class="loss">your ticket loses ${money(stake)}</strong>`}`;$('#runRace').disabled=false;if(ret>=stake*8)confetti()}},95)}}

