'use strict';

/* Neon Royale Horse Racing v5
   - The race simulation determines the winner. No winner is selected before the gates open.
   - Field compression keeps most races competitive while allowing occasional breakaways.
   - Track View gives each runner a distinct concentric lane.
   - Immersive View continuously reframes the live order and reveals a real finish line only in the stretch.
*/
(function horseRacingV5(){
  const U32=0x100000000;
  const TAKE=0.90;
  const HORSE_NAMES=[
    'Midnight Ace','Golden Circuit','Velvet Thunder','Lucky Comet','Royal Static','Emerald Rush',
    'Copper Crown','Blue Monarch','Solar Flare','Night Parade','Silver Ledger','Crimson Echo',
    'Desert Ghost','Harbor Lights','Kingmaker Run','Neon Phantom','Crown Jewel','Rapid Fortune',
    'Wild Horizon','Ivory Rocket','Storm Lantern','Velvet Arrow','Golden Harbor','Moonlit Rebel',
    'Scarlet Signal','Northern Rhythm','Electric Prince','Diamond Current','Grand Mirage','Lasting Glory'
  ];
  const SILKS=['#a53c45','#326aa3','#c79b2b','#7354a6','#258264','#d06e31','#a32974','#21686f','#7c4b22','#4356a9','#84342e','#4c7a2f'];
  const STORAGE_QUEUE='neonRoyaleHorseNameQueueV4';
  const STORAGE_RACE_NO='neonRoyaleHorseRaceNoV4';
  const STORAGE_VIEW='neonRoyaleHorseViewV4';

  function u32(){if(window.crypto?.getRandomValues){const a=new Uint32Array(1);window.crypto.getRandomValues(a);return a[0]}return Math.floor(Math.random()*U32)}
  function rand(){return u32()/U32}
  function randInt(n){n=Math.floor(n);if(n<=0)return 0;const limit=U32-(U32%n);let x;do{x=u32()}while(x>=limit);return x%n}
  function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=randInt(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
  function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
  function gcd(a,b){while(b){[a,b]=[b,a%b]}return Math.abs(a)||1}
  function frac(decimal){const profit=Math.max(.02,decimal-1);if(Math.abs(profit-1)<.06)return'EVS';const dens=profit<1?[4,5,8]:profit<2?[2,4]:profit<5?[1,2]:[1];let best={err:Infinity,n:1,d:1};for(const d of dens){const n=Math.max(1,Math.round(profit*d)),err=Math.abs(n/d-profit);if(err<best.err)best={err,n,d}}const g=gcd(best.n,best.d);return`${best.n/g}/${best.d/g}`}
  function ordinal(n){return n===1?'1ST':n===2?'2ND':n===3?'3RD':`${n}TH`}
  function nextRaceNumber(){const n=(Number(localStorage.getItem(STORAGE_RACE_NO))||0)+1;localStorage.setItem(STORAGE_RACE_NO,String(n));return n}
  function nextFieldNames(){let q=[];try{q=JSON.parse(localStorage.getItem(STORAGE_QUEUE)||'[]')}catch{}q=q.filter(x=>HORSE_NAMES.includes(x));if(q.length<6){const recent=new Set(q),fresh=shuffle(HORSE_NAMES.filter(n=>!recent.has(n)));q=[...q,...fresh]}const field=q.splice(0,6);localStorage.setItem(STORAGE_QUEUE,JSON.stringify(q));return field}

  function makeProbabilities(){
    let p=[
      .285+(rand()-.5)*.045,
      .215+(rand()-.5)*.040,
      .170+(rand()-.5)*.032,
      .135+(rand()-.5)*.028,
      .105+(rand()-.5)*.024,
      .045+(rand()-.5)*.022
    ].map(x=>Math.max(.018,x));
    const sum=p.reduce((a,b)=>a+b,0);p=p.map(x=>x/sum);return shuffle(p);
  }
  function marketSummary(probs,decimals){const order=probs.map((p,i)=>({p,i})).sort((a,b)=>b.p-a.p),fav=order[0],long=order.at(-1);return{favorite:fav.i,longshot:long.i,favOdds:frac(decimals[fav.i]),longOdds:frac(decimals[long.i])}}

  /* Odds influence expected pace, but only slightly. The actual race is generated by independent
     segment form, tactical surges, fatigue, drafting and position effects. */
  function raceProfiles(probs){
    const mean=1/6;
    return probs.map((p,i)=>({
      ability:1+(p-mean)*.11-(p<.08?.01:0),
      break:.94+(rand()-.5)*.16,
      backstretch:.96+(rand()-.5)*.18,
      turn:.95+(rand()-.5)*.19,
      kick:.95+(rand()-.5)*.22,
      stamina:.965+rand()*.07,
      phase:rand()*Math.PI*2,
      phase2:rand()*Math.PI*2,
      surgeStart:.13+rand()*.68,
      surgeWidth:.055+rand()*.10,
      surgePower:.012+rand()*.055,
      fadeStart:.55+rand()*.34,
      fadePower:rand()*.045,
      lane:i
    }))
  }
  function sectionFactor(h,t){return t<.17?h.break:t<.58?h.backstretch:t<.80?h.turn:h.kick}
  function rawSpeed(h,t){
    const rhythm=1+Math.sin(t*31+h.phase)*.018+Math.sin(t*67+h.phase2)*.010;
    const surgeDist=(t-h.surgeStart)/h.surgeWidth,surge=h.surgePower*Math.exp(-surgeDist*surgeDist);
    const fade=t>h.fadeStart?((t-h.fadeStart)/(1-h.fadeStart))*h.fadePower:0;
    return Math.max(.72,h.ability*sectionFactor(h,t)*h.stamina*rhythm+surge-fade)
  }

  function applyPackDynamics(speeds,dist,t,raceStyle){
    const order=Array.from({length:6},(_,i)=>i).sort((a,b)=>dist[b]-dist[a]);
    const lead=dist[order[0]],second=dist[order[1]],last=dist[order[5]],spread=lead-last;
    const maxSpread=raceStyle==='runaway'?.110:(t<.25?.055:t<.75?.072:.090);
    if(spread>maxSpread){
      order.forEach((idx,pos)=>{const rel=(lead-dist[idx])/Math.max(spread,.0001);speeds[idx]*=1+(rel-.30)*.075});
    }
    const leadGap=lead-second;
    if(raceStyle!=='runaway'&&leadGap>.035)speeds[order[0]]*=.972;
    if(raceStyle==='runaway'&&leadGap>.075)speeds[order[0]]*=.987;
    for(let pos=1;pos<6;pos++){const idx=order[pos],ahead=order[pos-1],gap=dist[ahead]-dist[idx];if(gap>0&&gap<.024)speeds[idx]*=1.012}
    return order;
  }

  function trackXY(progress,lane){
    const theta=progress*Math.PI*2-Math.PI/2;
    const rx=44-lane*1.45,ry=36-lane*1.10;
    return{x:50+Math.cos(theta)*rx,y:50+Math.sin(theta)*ry};
  }
  function miniXY(progress){const theta=progress*Math.PI*2-Math.PI/2;return{x:50+Math.cos(theta)*43,y:50+Math.sin(theta)*36}}
  function backToSportsbook(){goLobby();setTimeout(()=>document.getElementById('sportsbookLobbyCard')?.click(),0)}

  window.renderHorses=function renderHorsesV5(){
    const raceNo=nextRaceNumber(),names=nextFieldNames(),silks=shuffle(SILKS).slice(0,6),probs=makeProbabilities(),decimals=probs.map(p=>TAKE/p),fracs=decimals.map(frac),market=marketSummary(probs,decimals);
    state.horseBet=null;let racing=false,viewMode=localStorage.getItem(STORAGE_VIEW)==='immersive'?'immersive':'track';

    $('#gameMount').innerHTML=`<div class="casino-room room-horses horse-v5">
      <div class="horse-v4-nav"><button class="back-sportsbook-v4" id="horseBackSports">← Sportsbook</button><div><small>RACE ${String(raceNo).padStart(2,'0')}</small><b>ROYAL TURF CLUB</b></div></div>
      <div class="room-topline"><span class="rules-badge">LIVE RACE ENGINE · WINNER CROSSES FIRST · NEW FIELD EVERY RACE</span>${betControls('horseStake',100)}</div>
      <div class="horse-view-settings"><div><small>RACE CAMERA</small><b>Track View separates all six lanes. Immersive View follows the live front pack.</b></div><div class="horse-view-tabs"><button class="${viewMode==='track'?'active':''}" data-horse-view="track">TRACK VIEW</button><button class="${viewMode==='immersive'?'active':''}" data-horse-view="immersive">IMMERSIVE VIEW</button></div></div>
      <div class="racebook betting-only">
        <div class="race-call" id="raceCall">SELECT A RUNNER</div>
        <div class="horse-market-note"><span>FAVORITE <b>#${market.favorite+1} ${names[market.favorite]} · ${market.favOdds}</b></span><span>LONGSHOT <b>#${market.longshot+1} ${names[market.longshot]} · ${market.longOdds}</b></span></div>
        <div class="odds-board horse-v3-board"><div class="odds-head"><span>NO.</span><span>RUNNER</span><span>FRACTIONAL</span><span>DECIMAL</span><span>MODEL CHANCE</span></div>${names.map((n,i)=>`<div class="horse-line" data-horse="${i}"><span class="horse-silk" style="background:${silks[i]}">${i+1}</span><span class="horse-name"><b>${n}</b><small>${i===market.favorite?'FAVOURITE':i===market.longshot?'LONGSHOT':'Runner '+(i+1)}</small></span><span class="fractional-price">${fracs[i]}</span><span class="odds-price">${decimals[i].toFixed(2)}×</span><span class="chance">${(probs[i]*100).toFixed(1)}%</span></div>`).join('')}</div>
        <div class="horse-ticket-summary" id="horseTicket">Odds describe pre-race expectation. Once the gates open, the visible race itself determines the winner.</div>
        <div class="game-actions"><button class="primary-btn" id="runRace">PLACE BET &amp; GO TO TRACK</button><button class="secondary-btn" id="refreshRace">NEW RACE CARD</button></div>
      </div><div id="raceExperience" class="race-experience" aria-hidden="true"></div></div>`;

    wireQuickBets($('#gameMount'));$('#horseBackSports').onclick=backToSportsbook;$('#refreshRace').onclick=()=>{if(!racing)window.renderHorses()};
    $$('[data-horse-view]').forEach(b=>b.onclick=()=>{if(racing)return;viewMode=b.dataset.horseView;localStorage.setItem(STORAGE_VIEW,viewMode);$$('[data-horse-view]').forEach(x=>x.classList.toggle('active',x===b));pulse(b,'action-pulse')});
    $$('.horse-line').forEach(x=>x.onclick=()=>{if(racing)return;$$('.horse-line').forEach(y=>y.classList.remove('active'));x.classList.add('active');state.horseBet=+x.dataset.horse;pulse(x,'chip-drop');$('#raceCall').textContent=`TICKET · #${state.horseBet+1} ${names[state.horseBet]}`;$('#horseTicket').innerHTML=`<b>#${state.horseBet+1} ${names[state.horseBet]}</b><span>${fracs[state.horseBet]} · ${decimals[state.horseBet].toFixed(2)}× total return · ${(probs[state.horseBet]*100).toFixed(1)}% model chance · ${viewMode==='immersive'?'Immersive':'Track'} camera</span>`});

    $('#runRace').onclick=async()=>{
      if(racing)return;if(state.horseBet==null)return toast('Select a horse');const stake=getBet('horseStake');if(!stake)return;
      racing=true;adjust(-stake,{wager:true});recordGame('horses');
      const profiles=raceProfiles(probs),raceStyle=rand()<.12?'runaway':'tight',overlay=$('#raceExperience');
      overlay.innerHTML=`<div class="race-broadcast race-v5 ${viewMode==='immersive'?'immersive-camera':'track-camera'}">
        <header><div><small>NEON ROYALE TURF CLUB</small><b>RACE ${String(raceNo).padStart(2,'0')} · WIN MARKET</b></div><div class="broadcast-ticket"><small>YOUR HORSE</small><b>#${state.horseBet+1} ${names[state.horseBet]}</b><span>${fracs[state.horseBet]} · ${decimals[state.horseBet].toFixed(2)}×</span></div><div><small>CAMERA</small><b>${viewMode==='immersive'?'IMMERSIVE FRONT-PACK CAM':'SIX-LANE TRACK'}</b></div></header>
        <div class="race-countdown-screen" id="raceCountdown"><small>HORSES LOADING</small><strong>10</strong><span>GATES LOCKED</span></div>
        <div class="broadcast-track track-v5" id="broadcastTrack">
          <div class="track-view-layer"><div class="track-rail outer"></div><div class="track-rail inner"></div><div class="track-infield"><b>NEON ROYALE</b><span>TURF CLUB</span></div><div class="start-finish-line"></div>${Array.from({length:6},(_,i)=>`<div class="track-lane-ring lane-${i}"></div>`).join('')}${names.map((n,i)=>`<div class="broadcast-horse track-horse-v5 ${i===state.horseBet?'your-horse':''}" id="broadcastHorse${i}"><i style="--silk:${silks[i]}">${i+1}</i><span>🏇</span><small>${n}</small></div>`).join('')}<div class="race-mini-map"><b>TRACK MAP</b><div class="mini-oval">${names.map((_,i)=>`<i id="miniHorse${i}" style="--silk:${silks[i]}">${i+1}</i>`).join('')}</div></div></div>
          <div class="immersive-view-layer"><div class="immersive-rail top"></div><div class="immersive-track-scroll"></div><div class="immersive-speed-lines"></div><div class="immersive-rail bottom"></div><div class="immersive-camera-label"><small>LIVE</small><b>FRONT PACK</b><span id="cameraLeader">RACE FORMING</span></div><div class="immersive-finish" id="immersiveFinish"><span>FINISH</span></div>${names.map((n,i)=>`<div class="immersive-horse immersive-horse-v5 ${i===state.horseBet?'your-horse':''}" id="immersiveHorse${i}"><span class="immersive-no" style="--silk:${silks[i]}">${i+1}</span><span class="immersive-runner">🏇</span><small>${n}</small></div>`).join('')}</div>
          <div class="race-leaderboard" id="raceLeaderboard"></div>
        </div>
        <footer><div><small>RACE TIME</small><b id="raceClock">00:00.0</b></div><div class="race-commentary" id="raceCommentary">Loading into the starting gate…</div><div><small>YOUR POSITION</small><b id="yourPosition">—</b></div></footer></div>`;
      overlay.classList.add('active');overlay.setAttribute('aria-hidden','false');document.body.classList.add('race-mode');await afterPaint();
      const cd=$('#raceCountdown strong');for(let t=10;t>=1;t--){cd.textContent=t;pulse(cd,'countdown-pop');await wait(1000)}$('#raceCountdown small').textContent="THEY'RE SET";cd.textContent='GO';$('#raceCountdown span').textContent='GATES OPEN';pulse(cd,'countdown-pop');await wait(620);$('#raceCountdown').classList.add('gone');

      const trackHorses=names.map((_,i)=>$('#broadcastHorse'+i)),immersiveHorses=names.map((_,i)=>$('#immersiveHorse'+i)),mini=names.map((_,i)=>$('#miniHorse'+i));
      const targetDuration=prefersReducedMotion()?8000:45000+randInt(9001),start=performance.now(),dist=Array(6).fill(0);let lastNow=start,lastLeader=-1,commentAt=0,winner=-1,finishTime=0;
      await new Promise(resolve=>{function frame(now){
        const elapsed=now-start,t=clamp(elapsed/targetDuration,0,1.30),dt=Math.min(.035,Math.max(0,(now-lastNow)/targetDuration));lastNow=now;
        const speeds=profiles.map(h=>rawSpeed(h,clamp(t,0,1)));
        applyPackDynamics(speeds,dist,clamp(t,0,1),raceStyle);
        const paceScale=1.02;
        for(let i=0;i<6;i++)dist[i]+=speeds[i]*dt*paceScale;
        const order=Array.from({length:6},(_,i)=>i).sort((a,b)=>dist[b]-dist[a]),leader=order[0],leaderDist=dist[leader],trailerDist=dist[order[5]];
        if(winner<0&&leaderDist>=1){winner=leader;finishTime=elapsed}

        for(let i=0;i<6;i++){
          const p=clamp(dist[i],0,1.018),xy=trackXY(p,i),mxy=miniXY(Math.min(1.01,p));
          trackHorses[i].style.left=`${xy.x}%`;trackHorses[i].style.top=`${xy.y}%`;trackHorses[i].style.zIndex=String(20+Math.round(xy.y));
          mini[i].style.left=`${mxy.x}%`;mini[i].style.top=`${mxy.y}%`;
        }

        const spread=Math.max(.022,leaderDist-trailerDist),finish=$('#immersiveFinish');
        let finishX=132;
        if(leaderDist>.88){finishX=72+(1-leaderDist)*500;finish.classList.add('stretch')}else finish.classList.remove('stretch');
        finish.style.left=`${finishX}%`;
        for(let i=0;i<6;i++){
          let x;
          if(leaderDist>.88)x=finishX-(1-dist[i])*500;
          else x=72-(leaderDist-dist[i])/spread*64;
          x=clamp(x,4,96);
          const y=15+i*13.5+Math.sin(elapsed/330+i*1.4)*1.4;
          immersiveHorses[i].style.left=`${x}%`;immersiveHorses[i].style.top=`${y}%`;
          immersiveHorses[i].style.zIndex=String(40+i);
        }

        $('#raceClock').textContent=`00:${String(Math.floor(elapsed/1000)).padStart(2,'0')}.${Math.floor((elapsed%1000)/100)}`;
        const yourRank=order.indexOf(state.horseBet)+1;$('#yourPosition').textContent=`${ordinal(yourRank)} / 6`;
        $('#raceLeaderboard').innerHTML=order.slice(0,3).map((idx,pos)=>`<span class="${idx===state.horseBet?'you':''}"><b>${pos+1}</b>#${idx+1} ${names[idx]}</span>`).join('');
        $('#cameraLeader').textContent=`#${leader+1} ${names[leader]}`;
        if(leader!==lastLeader||elapsed-commentAt>4200){const old=lastLeader;lastLeader=leader;commentAt=elapsed;let text;if(old>=0&&old!==leader)text=`#${leader+1} ${names[leader]} moves past #${old+1} ${names[old]} for the lead!`;else if(leaderDist<.25)text=`#${leader+1} ${names[leader]} has the early advantage, but the field is tightly packed.`;else if(leaderDist<.72)text=`#${leader+1} ${names[leader]} leads with challengers stacked up behind.`;else if(leaderDist<.90)text=`They hit the final turn — #${leader+1} ${names[leader]} is under pressure.`;else text=`Into the stretch! #${leader+1} ${names[leader]} has company!`;$('#raceCommentary').textContent=text;pulse($('#raceCommentary'),'status-pulse')}

        if(winner>=0&&elapsed-finishTime>700){resolve();return}requestAnimationFrame(frame)
      }requestAnimationFrame(frame)});

      trackHorses[winner].classList.add('broadcast-winner');immersiveHorses[winner].classList.add('immersive-winner');$('#raceCommentary').textContent=`PHOTO — #${winner+1} ${names[winner]} GETS THERE FIRST!`;pulse($('#raceCommentary'),'result-pop');
      const ret=winner===state.horseBet?stake*decimals[winner]:0;if(ret)adjust(ret,{win:true});await wait(1500);
      overlay.insertAdjacentHTML('beforeend',`<div class="race-result-overlay"><small>OFFICIAL RESULT · RACE ${String(raceNo).padStart(2,'0')}</small><h2>#${winner+1} ${names[winner]}</h2><p>${winner===state.horseBet?`Your ${fracs[winner]} ticket returns <b>${money(ret)}</b>.`:`Your #${state.horseBet+1} ${names[state.horseBet]} ticket did not win.`}</p><div class="race-result-actions"><button class="gold-btn" id="nextRaceCard">NEXT RACE · NEW FIELD</button><button class="glass-btn" id="raceBackSports">RETURN TO SPORTSBOOK</button></div></div>`);
      if(ret>=stake*8)confetti();$('#nextRaceCard').onclick=()=>{overlay.classList.remove('active');overlay.setAttribute('aria-hidden','true');document.body.classList.remove('race-mode');overlay.innerHTML='';racing=false;state.horseBet=null;window.renderHorses()};$('#raceBackSports').onclick=()=>{overlay.classList.remove('active');document.body.classList.remove('race-mode');backToSportsbook()};
    };
  };

  const priorShowTutorial=window.showTutorial;
  window.showTutorial=function horseV5Tutorial(game){if(game==='horses')return showModal(`<p class="kicker">ROYAL TURF CLUB · LIVE RACE ENGINE</p><h2>Horse Racing</h2><p>The race no longer selects a winner before the gates open. Posted odds describe pre-race expectations, but the six horses then run an independent live pace simulation. Breaks, surges, drafting, fading and closing speed continuously change their order. <b>The first horse whose simulated distance reaches the finish is the winner.</b></p><div class="modal-grid"><div class="modal-card"><b>Track View</b><small>All six horses occupy visibly separate concentric lanes around the oval so their numbers remain readable.</small></div><div class="modal-card"><b>Immersive View</b><small>The camera uses real relative distance, so passes visibly happen on screen. The finish line stays hidden until the field reaches the stretch, then horses physically cross it.</small></div></div><p>Most races use a competitive pack model to create GTA-style tension. About 12% permit a more pronounced breakaway so not every finish looks identical.</p>`);return priorShowTutorial?priorShowTutorial(game):undefined};
})();
