'use strict';

/* Neon Royale Integrity Pass v1
   Visual state is authoritative for roulette, slots, Keno and Craps.
   Card games keep physical shuffled shoes/decks; sport/race engines already resolve from visible simulation.
*/
(function integrityPassV1(){
  const U32=0x100000000;
  const unit=()=>{if(window.crypto?.getRandomValues){const a=new Uint32Array(1);window.crypto.getRandomValues(a);return a[0]/U32}return Math.random()};
  const ri=n=>Math.floor(unit()*n);
  const shuffleLocal=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=ri(i+1);[a[i],a[j]]=[a[j],a[i]]}return a};
  const sleep=ms=>new Promise(r=>setTimeout(r,prefersReducedMotion()?Math.min(ms,45):ms));
  const norm=d=>((d%360)+360)%360;

  const WHEEL=['0','28','9','26','30','11','7','20','32','17','5','22','34','15','3','24','36','13','1','00','27','10','25','29','12','8','19','31','18','6','21','33','16','4','23','35','14','2'];
  const RED=new Set(['1','3','5','7','9','12','14','16','18','19','21','23','25','27','30','32','34','36']);
  const sector=360/WHEEL.length;
  const pocketColor=n=>(n==='0'||n==='00')?'green':RED.has(n)?'red':'black';
  const gradient=()=>`conic-gradient(from ${-sector/2}deg,${WHEEL.map((n,i)=>`${pocketColor(n)==='green'?'#087c48':pocketColor(n)==='red'?'#a8232b':'#171717'} ${i*sector}deg ${(i+1)*sector}deg`).join(',')})`;
  function pocketUnderPointer(rotation){const internal=norm(-rotation),idx=Math.floor((internal+sector/2)/sector)%38;return {idx,value:WHEEL[idx]};}
  function roulettePayout(type,result,stake){const n=Number(result);let won=false,m=0;if(type.startsWith('n:')){won=type.slice(2)===result;m=35}else if(!['0','00'].includes(result)){if(type==='red')won=RED.has(result);if(type==='black')won=!RED.has(result);if(type==='odd')won=n%2===1;if(type==='even')won=n%2===0;if(type==='low')won=n<=18;if(type==='high')won=n>=19;if(type==='d1')won=n<=12;if(type==='d2')won=n>=13&&n<=24;if(type==='d3')won=n>=25;m=['d1','d2','d3'].includes(type)?2:1}return {won,profitMult:m,ret:won?stake*(m+1):0};}
  function speakRoulette(value,color){try{if(!window.speechSynthesis)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(`${value==='00'?'double zero':value}, ${color.toLowerCase()}`);u.rate=1.05;u.volume=.8;window.speechSynthesis.speak(u)}catch{}}

  window.renderRoulette=function renderRouletteIntegrity(){
    state.rouletteBet=null;let spinning=false,rotation=0,lastTick=-1;
    const labels=WHEEL.map((n,i)=>`<span class="ri-pocket ri-${pocketColor(n)}" data-pocket="${i}" style="transform:translate(-50%,-50%) rotate(${i*sector}deg) translateY(-118px) rotate(90deg)">${n}</span>`).join('');
    $('#gameMount').innerHTML=`<div class="casino-room room-roulette roulette-integrity"><div class="room-topline"><span class="rules-badge">AMERICAN WHEEL · 38 PHYSICAL POCKETS · POINTER DECIDES</span>${betControls('rouletteStake',100)}</div><div class="roulette-stage"><div class="roulette-machine ri-machine"><div class="roulette-call" id="rouletteCall">PLACE YOUR BETS</div><div class="ri-pointer" id="riPointer">▼</div><div class="ri-wheel-shell"><div class="ri-wheel" id="rouletteWheel" style="background:${gradient()}"><div class="ri-hub"><b>NR</b><small>ROULETTE</small></div>${labels}</div></div><div class="roulette-result" id="rouletteResult">—</div><small class="ri-integrity-note">The wheel's final angle is read under the fixed pointer. No pocket is selected separately.</small></div><div class="betting-board"><p class="kicker">PLACE BET</p><div class="selected-bet" id="selectedRouletteBet">No bet selected</div><div class="roulette-numbers">${['0','00',...Array.from({length:36},(_,i)=>String(i+1))].map(n=>`<button class="roulette-bet-btn ${n==='0'||n==='00'?'green':rouletteReds.has(+n)?'red':'black'}" data-rbet="n:${n}">${n}</button>`).join('')}</div><div class="outside-bets">${[['red','RED'],['black','BLACK'],['odd','ODD'],['even','EVEN'],['low','1–18'],['high','19–36'],['d1','1st 12'],['d2','2nd 12'],['d3','3rd 12']].map(([k,l])=>`<button class="roulette-bet-btn" data-rbet="${k}">${l}</button>`).join('')}</div><div class="game-actions"><button class="primary-btn" id="spinRoulette">SPIN WHEEL</button></div><div id="rouletteBanner" class="result-banner">Straight 35:1 · Dozens 2:1 · Even-money 1:1</div></div></div></div>`;
    wireQuickBets($('#gameMount'));
    $$('[data-rbet]').forEach(b=>b.onclick=()=>{if(spinning)return;$$('[data-rbet]').forEach(x=>x.classList.remove('active'));b.classList.add('active');pulse(b,'chip-drop');state.rouletteBet=b.dataset.rbet;$('#selectedRouletteBet').textContent='Selected: '+b.textContent.trim()});
    $('#spinRoulette').onclick=async()=>{if(spinning)return;if(!state.rouletteBet)return toast('Choose a roulette bet');const stake=getBet('rouletteStake');if(!stake)return;spinning=true;adjust(-stake,{wager:true});recordGame('roulette');$('#spinRoulette').disabled=true;$$('[data-rbet]').forEach(b=>b.disabled=true);const call=$('#rouletteCall'),wheel=$('#rouletteWheel'),pointer=$('#riPointer');call.textContent='NO MORE BETS';call.classList.add('live');$('#rouletteResult').textContent='SPINNING';
      const start=rotation,turns=8+ri(5),release=unit()*360,target=start+turns*360+release,duration=prefersReducedMotion()?900:5000+ri(901),t0=performance.now();
      await new Promise(resolve=>{function frame(now){const t=Math.min(1,(now-t0)/duration),ease=1-Math.pow(1-t,5),r=start+(target-start)*ease;wheel.style.transform=`rotate(${r}deg)`;const p=pocketUnderPointer(r);if(p.idx!==lastTick){lastTick=p.idx;pointer.classList.remove('tick');void pointer.offsetWidth;pointer.classList.add('tick')}if(t<1)requestAnimationFrame(frame);else{rotation=target;resolve()}}requestAnimationFrame(frame)});
      const {idx,value:result}=pocketUnderPointer(rotation),color=pocketColor(result).toUpperCase();$$('.ri-pocket').forEach(x=>x.classList.remove('winner'));$(`.ri-pocket[data-pocket="${idx}"]`)?.classList.add('winner');call.textContent='WINNING POCKET';$('#rouletteResult').textContent=`${result} · ${color}`;pulse($('#rouletteResult'),'result-pop');speakRoulette(result,color);const pay=roulettePayout(state.rouletteBet,result,stake);if(pay.ret)adjust(pay.ret,{win:true});$('#rouletteBanner').innerHTML=pay.won?`<strong class="win">WIN · ${money(pay.ret)} returned</strong>`:`<strong class="loss">LOSE · ${money(stake)}</strong>`;await sleep(900);call.textContent='PLACE YOUR BETS';call.classList.remove('live');$('#spinRoulette').disabled=false;$$('[data-rbet]').forEach(b=>b.disabled=false);spinning=false;if(pay.won&&pay.profitMult===35)confetti();
    };
  };

  const SLOT_SYMBOLS=[{key:'blank',display:'•',label:'Blank',count:24,pct:48},{key:'cherry',display:'🍒',label:'Cherry',count:10,pct:20},{key:'lemon',display:'🍋',label:'Lemon',count:6,pct:12},{key:'bell',display:'🔔',label:'Bell',count:4,pct:8},{key:'bar',display:'BAR',label:'BAR',count:3,pct:6},{key:'seven',display:'7',label:'Seven',count:2,pct:4},{key:'diamond',display:'◆',label:'Diamond',count:1,pct:2}];
  const BY=Object.fromEntries(SLOT_SYMBOLS.map(s=>[s.key,s])),POOL=SLOT_SYMBOLS.flatMap(s=>Array(s.count).fill(s.key));
  const THREE={cherry:25,lemon:35,bell:60,bar:125,seven:250,diamond:1000};
  const FIVE={cherry:{3:55,4:110,5:275},lemon:{3:85,4:215,5:535},bell:{3:135,4:375,5:1070},bar:{3:215,4:800,5:2675},seven:{3:430,4:1600,5:6400},diamond:{3:960,4:4800,5:24000}};
  const LINES=[[0,0,0,0,0],[1,1,1,1,1],[2,2,2,2,2],[0,1,2,1,0],[2,1,0,1,2],[0,0,1,2,2],[2,2,1,0,0],[1,0,0,0,1],[1,2,2,2,1]];
  const sym=k=>`<span class="slot-symbol ${k==='blank'?'slot-blank':''}">${BY[k].display}</span>`;
  function visible(strip,stop){const n=strip.length;return [strip[(stop-1+n)%n],strip[stop%n],strip[(stop+1)%n]]}
  function score3(matrix){const [a,b,c]=matrix.map(x=>x[1]);let m=0,label='No winning combination',count=0;if(a===b&&b===c&&a!=='blank'){m=THREE[a]||0;label=`Three ${BY[a].label}s`;count=3}else if(a==='cherry'&&b==='cherry'){m=8;label='Cherry · Cherry · Any';count=2}else if(a==='cherry'){m=2;label='Cherry · Any · Any';count=1}const cells=new Set();for(let i=0;i<count;i++)cells.add(`${i}-1`);return{mult:m,label,cells}}
  function score5(matrix,stake){const lineBet=stake/LINES.length,wins=[],cells=new Set();let totalReturn=0;LINES.forEach((rows,li)=>{const keys=rows.map((row,reel)=>matrix[reel][row]),first=keys[0];if(first==='blank')return;let c=1;while(c<keys.length&&keys[c]===first)c++;if(c<3)return;const m=FIVE[first]?.[c]||0;if(!m)return;const lr=lineBet*m;totalReturn+=lr;for(let r=0;r<c;r++)cells.add(`${r}-${rows[r]}`);wins.push({line:li+1,key:first,count:c,mult:m,lineReturn:lr})});return{totalReturn,wins,cells}}
  function paytable(mode){if(mode===3)return `<p class="kicker">ROYAL REELS</p><h2>Classic 3-Reel Paytable</h2><div class="slot-paytable-grid slot-paytable-classic"><span>◆ ◆ ◆</span><b>1000×</b><span>7 · 7 · 7</span><b>250×</b><span>BAR · BAR · BAR</span><b>125×</b><span>🔔 🔔 🔔</span><b>60×</b><span>🍋 🍋 🍋</span><b>35×</b><span>🍒 🍒 🍒</span><b>25×</b><span>🍒 🍒 ANY</span><b>8×</b><span>🍒 ANY ANY</span><b>2×</b></div>`;return `<p class="kicker">ROYAL REELS</p><h2>Modern 5-Reel Paytable</h2><p>9 paylines. Three or more matching symbols must begin on reel 1 and continue left-to-right.</p><div class="slot-paytable-scroll"><table class="slot-paytable-table"><thead><tr><th>Symbol</th><th>3</th><th>4</th><th>5</th></tr></thead><tbody>${SLOT_SYMBOLS.filter(s=>s.key!=='blank').map(s=>`<tr><td>${s.display} ${s.label}</td><td>${FIVE[s.key][3]}×</td><td>${FIVE[s.key][4]}×</td><td>${FIVE[s.key][5]}×</td></tr>`).join('')}</tbody></table></div>`}

  window.renderSlots=function renderSlotsIntegrity(){let mode=5,spinning=false,strips=[],positions=[];const build=()=>{strips=Array.from({length:mode},()=>shuffleLocal(POOL));positions=Array.from({length:mode},()=>ri(POOL.length))};build();
    $('#gameMount').innerHTML=`<div class="casino-room room-slots slot-v2 slot-integrity"><div class="room-topline"><span class="rules-badge" id="slotRulesBadge">MODERN 5-REEL · PHYSICAL DETENT STOPS</span>${betControls('slotBet',25)}</div><div class="slot-mode-row"><div class="slot-mode-switch"><button data-slot-mode="3">CLASSIC 3-REEL</button><button data-slot-mode="5" class="active">MODERN 5-REEL</button></div><div class="slot-help-actions"><button class="glass-btn slot-small-btn" id="slotPaytableBtn">VIEW PAYTABLE</button><button class="glass-btn slot-small-btn" id="slotHowBtn">HOW IT WORKS</button></div></div><div class="slot-cabinet modern-five" id="slotCabinet"><div class="slot-lights"></div><div class="slot-marquee"><small>NEON ROYALE</small> ROYAL REELS</div><div class="slot-machine-subtitle" id="slotSubtitle">5 REELS · 3 ROWS · 9 ACTIVE PAYLINES</div><div class="integrity-reel-bank five" id="slotReelBank"></div><div class="slot-display" id="slotDisplay">PRESS SPIN · THE REELS DECIDE</div><div class="game-actions"><button class="primary-btn slot-spin-button" id="slotSpin">SPIN</button></div><div class="slot-frequency-panel"><div><b>FIXED REEL STRIP FREQUENCY</b><small>Each reel has 50 fixed stops. The center row after the reel physically settles is the result.</small></div><div class="slot-frequency-list">${SLOT_SYMBOLS.map(s=>`<span><i>${s.display}</i>${s.label} <b>${s.pct}%</b></span>`).join('')}</div></div></div></div>`;
    wireQuickBets($('#gameMount'));const bank=$('#slotReelBank'),display=$('#slotDisplay'),cab=$('#slotCabinet');
    function paintReels(){bank.className=`integrity-reel-bank ${mode===3?'three':'five'}`;bank.innerHTML=strips.map((strip,i)=>`<div class="integrity-reel-window" data-reel="${i}"><div class="integrity-reel-track">${[...strip,...strip,...strip].map(k=>`<div class="integrity-reel-cell">${sym(k)}</div>`).join('')}</div></div>`).join('');positions.forEach((p,i)=>setReel(i,p,false))}
    function setReel(i,p,animate=false){const track=bank.querySelector(`[data-reel="${i}"] .integrity-reel-track`);if(!track)return;track.style.transition=animate?'transform .16s cubic-bezier(.2,.8,.2,1)':'none';const y=(POOL.length+(p%POOL.length)-1)*68;track.style.transform=`translateY(-${y}px)`}
    function matrix(){return strips.map((s,i)=>visible(s,Math.round(positions[i])%s.length))}
    function clearHi(){$$('.integrity-reel-cell',bank).forEach(x=>x.classList.remove('slot-winning-cell'))}
    function highlight(cells){cells.forEach(tok=>{const [reel,row]=tok.split('-').map(Number),win=bank.querySelector(`[data-reel="${reel}"]`),vis=[...win.querySelectorAll('.integrity-reel-cell')].slice(POOL.length+Math.round(positions[reel])%POOL.length-1,POOL.length+Math.round(positions[reel])%POOL.length+2);vis[row]?.classList.add('slot-winning-cell')})}
    async function physicalSpin(){clearHi();const reels=strips.length,vel=Array.from({length:reels},(_,i)=>82+unit()*16+i*4),fric=Array.from({length:reels},(_,i)=>18.5+unit()*2.8-i*.22),alive=Array(reels).fill(true),last=performance.now();await new Promise(resolve=>{function frame(now){const dt=Math.min(.035,(now-last)/1000);last=now;let any=false;for(let i=0;i<reels;i++){if(!alive[i])continue;vel[i]=Math.max(0,vel[i]-fric[i]*dt);positions[i]+=vel[i]*dt;setReel(i,positions[i],false);if(vel[i]<=0){alive[i]=false;positions[i]=Math.round(positions[i])%POOL.length;setReel(i,positions[i],true);pulse(bank.querySelector(`[data-reel="${i}"]`),'reel-window-stop')}else any=true}if(any)requestAnimationFrame(frame);else setTimeout(resolve,prefersReducedMotion()?20:190)}requestAnimationFrame(frame)})}
    function modeSet(m){if(spinning||m===mode)return;mode=m;build();$$('[data-slot-mode]').forEach(b=>b.classList.toggle('active',+b.dataset.slotMode===mode));cab.classList.toggle('classic-three',mode===3);cab.classList.toggle('modern-five',mode===5);$('#slotRulesBadge').textContent=mode===3?'CLASSIC 3-REEL · PHYSICAL DETENT STOPS':'MODERN 5-REEL · PHYSICAL DETENT STOPS';$('#slotSubtitle').textContent=mode===3?'3 REELS · CENTER ROW PAYS':'5 REELS · 3 ROWS · 9 ACTIVE PAYLINES';paintReels();display.textContent='PRESS SPIN · THE REELS DECIDE'}
    $$('[data-slot-mode]').forEach(b=>b.onclick=()=>modeSet(+b.dataset.slotMode));$('#slotPaytableBtn').onclick=()=>showModal(paytable(mode));$('#slotHowBtn').onclick=()=>showModal(`<p class="kicker">ROYAL REELS INTEGRITY</p><h2>The visible stop is the result</h2><p>Each reel has a fixed 50-stop strip. A spin gives each reel an independent starting velocity and friction. The reel slows, snaps into the nearest physical detent, and the symbols visibly resting in the window are then scored. No winning symbol combination is selected separately.</p>${paytable(mode)}`);
    $('#slotSpin').onclick=async()=>{if(spinning)return;const stake=getBet('slotBet');if(!stake)return;spinning=true;adjust(-stake,{wager:true});recordGame('slots');$('#slotSpin').disabled=true;cab.classList.add('machine-live');display.textContent='REELS IN MOTION…';await physicalSpin();const m=matrix();if(mode===3){const r=score3(m),ret=stake*r.mult;if(ret)adjust(ret,{win:true});highlight(r.cells);display.textContent=ret?`${r.label.toUpperCase()} · RETURN ${money(ret)}`:`NO WIN · -${money(stake)}`;if(ret>=stake*50)confetti()}else{const r=score5(m,stake),ret=r.totalReturn;if(ret)adjust(ret,{win:true});highlight(r.cells);display.textContent=ret?`${r.wins.length} PAYLINE${r.wins.length===1?'':'S'} · RETURN ${money(ret)}`:`NO WINNING PAYLINE · -${money(stake)}`;if(ret>=stake*50)confetti()}cab.classList.remove('machine-live');$('#slotSpin').disabled=false;spinning=false};paintReels();
  };

  const KP={1:{1:3.6},2:{2:15},3:{2:2,3:45},4:{2:1.25,3:6.5,4:115},5:{3:3.25,4:25,5:500},6:{3:1.4,4:7,5:110,6:1400},7:{3:1.5,4:3,5:27.5,6:225,7:3000},8:{4:3.4,5:13.5,6:85,7:850,8:8500},9:{4:1.6,5:8,6:40,7:240,8:2400,9:16000},10:{5:4.5,6:22.5,7:112.5,8:1125,9:11250,10:45000}};
  window.renderKeno=function renderKenoIntegrity(){let picks=[],drawing=false;$('#gameMount').innerHTML=`<div class="casino-room room-keno"><div class="room-topline"><span class="rules-badge">20 / 80 · EACH BALL DRAWN LIVE WITHOUT REPLACEMENT</span>${betControls('kenoBet',25)}</div><div class="keno-stage"><div class="keno-board"><div class="keno-board-header"><b>KENO NUMBER BOARD</b><span id="pickCount">0 / 10 SELECTED</span></div><div class="keno-caller" id="kenoCaller"><small>LIVE BALL</small><strong>READY</strong></div><div class="number-grid">${Array.from({length:80},(_,i)=>`<button class="keno-num" data-n="${i+1}">${i+1}</button>`).join('')}</div><div class="game-actions"><button class="secondary-btn" id="quickPick">Quick Pick 10</button><button class="secondary-btn" id="clearKeno">Clear</button><button class="primary-btn" id="drawKeno">DRAW 20 NUMBERS</button></div></div><aside class="keno-side"><div class="keno-ticket"><p class="kicker">YOUR TICKET</p><h3>Selected Spots</h3><div class="pick-readout" id="pickReadout">Choose at least one number.</div><div class="draw-balls" id="drawBalls"></div><div id="kenoResult"></div></div><div class="paytable-card"><p class="kicker">ACTIVE PAYTABLE</p><h3>Return multiplier</h3><div id="kenoPayMini" class="paytable-mini"></div></div></aside></div></div>`;wireQuickBets($('#gameMount'));
    const paint=()=>{$$('.keno-num').forEach(b=>b.classList.toggle('selected',picks.includes(+b.dataset.n)));$('#pickCount').textContent=`${picks.length} / 10 SELECTED`;$('#pickReadout').textContent=picks.length?picks.slice().sort((a,b)=>a-b).join(' · '):'Choose at least one number.';const p=KP[picks.length]||{};$('#kenoPayMini').innerHTML=Object.keys(p).length?Object.entries(p).map(([h,m])=>`<span>${h} hit${h==='1'?'':'s'}</span><b>${m}×</b>`).join(''):'<span>Select spots to view payouts.</span>'};
    $$('.keno-num').forEach(b=>b.onclick=()=>{if(drawing)return;const n=+b.dataset.n;if(picks.includes(n))picks=picks.filter(x=>x!==n);else if(picks.length<10)picks.push(n);else return toast('Maximum 10 Keno spots');paint();pulse(b,'pick-pop')});$('#quickPick').onclick=()=>{if(drawing)return;picks=shuffleLocal(Array.from({length:80},(_,i)=>i+1)).slice(0,10);paint()};$('#clearKeno').onclick=()=>{if(drawing)return;picks=[];paint();$('#drawBalls').innerHTML='';$('#kenoResult').innerHTML='';$('#kenoCaller strong').textContent='READY';$$('.keno-num').forEach(b=>b.classList.remove('drawn','hit'))};
    $('#drawKeno').onclick=async()=>{if(drawing)return;if(!picks.length)return toast('Pick at least one number');const bet=getBet('kenoBet');if(!bet)return;drawing=true;adjust(-bet,{wager:true});recordGame('keno');const remaining=Array.from({length:80},(_,i)=>i+1),draw=[],balls=$('#drawBalls');balls.innerHTML='';$('#kenoResult').innerHTML='<div class="result-banner">Live draw in progress…</div>';$$('.keno-num').forEach(b=>b.classList.remove('drawn','hit'));for(let i=0;i<20;i++){const idx=ri(remaining.length),n=remaining.splice(idx,1)[0];draw.push(n);const hit=picks.includes(n),cell=$(`.keno-num[data-n="${n}"]`);$('#kenoCaller strong').textContent=n;balls.insertAdjacentHTML('beforeend',`<span class="draw-ball ${hit?'hit':''}">${n}</span>`);cell.classList.add('drawn');if(hit)cell.classList.add('hit');pulse($('#kenoCaller'),'caller-pop');if(hit)pulse(cell,'hit-pop');await sleep(115)}const hits=draw.filter(n=>picks.includes(n)),mult=(KP[picks.length]||{})[hits.length]||0,ret=bet*mult;if(ret)adjust(ret,{win:true});$('#kenoCaller strong').textContent='COMPLETE';$('#kenoResult').innerHTML=`<div class="result-banner">Hit <b>${hits.length}</b> of ${picks.length}. ${ret?`<strong class="win">Return ${money(ret)}</strong>`:`<strong class="loss">No payout</strong>`}</div>`;if(ret>=bet*50)confetti();drawing=false};paint();
  };

  async function physicalDice(){const d1=$('#die1'),d2=$('#die2'),faces=['⚀','⚁','⚂','⚃','⚄','⚅'];let a=1,b=1;d1.classList.add('dice-roll');d2.classList.add('dice-roll');const steps=prefersReducedMotion()?4:14+ri(5);for(let i=0;i<steps;i++){a=1+ri(6);b=1+ri(6);d1.dataset.face=a;d2.dataset.face=b;d1.textContent=faces[a-1];d2.textContent=faces[b-1];await sleep(48+Math.floor(i*5.5))}d1.classList.remove('dice-roll');d2.classList.remove('dice-roll');pulse(d1,'reel-stop');pulse(d2,'reel-stop');return [Number(d1.dataset.face),Number(d2.dataset.face)]}
  function crapsHelpIntegrity(){showModal('<p class="kicker">CRAPS</p><h2>Visible dice decide the roll</h2><p><b>Pass Line:</b> come-out 7/11 wins; 2/3/12 loses. A point must repeat before 7. <b>Don’t Pass:</b> reverses that, with 12 pushing. <b>Field:</b> is one roll on 2,3,4,9,10,11,12.</p><div class="modal-card"><b>Integrity</b><small>The dice tumble through visible faces. The final two faces left on the table are read directly and scored. There is no separate hidden dice result.</small></div>')}
  function openCrapsIntegrity(){currentGame='craps';document.body.dataset.room='craps';$('#lobbyView').classList.remove('active');$('#gameView').classList.add('active');$('#gameTitle').textContent='Craps';$('#gameEyebrow').textContent='ROYAL GAMING HALL';$('#gameSubtitle').textContent='Pass Line · Don’t Pass · Field · visible dice';$('#gameHelpBtn').onclick=crapsHelpIntegrity;renderCrapsIntegrity();scrollTo({top:0,behavior:'smooth'})}
  function renderCrapsIntegrity(){let betType='pass',busy=false;$('#gameMount').innerHTML=`<div class="casino-room craps-v1 craps-integrity"><div class="room-topline"><span class="rules-badge">TWO FAIR DICE · FINAL VISIBLE FACES DECIDE</span>${betControls('crapsStake',25)}</div><div class="craps-table"><div class="craps-bets"><button data-craps="pass" class="active">PASS LINE</button><button data-craps="dont">DON’T PASS</button><button data-craps="field">FIELD</button></div><div class="dice-stage"><div class="die" id="die1" data-face="5">⚄</div><div class="die" id="die2" data-face="3">⚂</div></div><div class="craps-point" id="crapsPoint">COME-OUT ROLL</div><div class="game-actions"><button class="primary-btn" id="rollCraps">ROLL DICE</button></div><div class="result-banner" id="crapsResult">Choose a wager and roll.</div></div></div>`;wireQuickBets($('#gameMount'));$$('[data-craps]').forEach(b=>b.onclick=()=>{if(busy)return;$$('[data-craps]').forEach(x=>x.classList.remove('active'));b.classList.add('active');betType=b.dataset.craps});$('#rollCraps').onclick=async()=>{if(busy)return;const stake=getBet('crapsStake');if(!stake)return;busy=true;adjust(-stake,{wager:true});recordGame('craps');let point=null,done=false,ret=0;while(!done){const [d1,d2]=await physicalDice(),sum=d1+d2;$('#crapsResult').textContent=`${d1} + ${d2} = ${sum}`;if(betType==='field'){if([2,3,4,9,10,11,12].includes(sum)){const mult=sum===12?4:sum===2?3:2;ret=stake*mult}done=true;break}if(point==null){if(betType==='pass'){if([7,11].includes(sum)){ret=stake*2;done=true}else if([2,3,12].includes(sum))done=true;else{point=sum;$('#crapsPoint').textContent=`POINT ${point}`;await sleep(450)}}else{if([2,3].includes(sum)){ret=stake*2;done=true}else if([7,11].includes(sum))done=true;else if(sum===12){ret=stake;done=true}else{point=sum;$('#crapsPoint').textContent=`POINT ${point}`;await sleep(450)}}}else{if(sum===point){ret=betType==='pass'?stake*2:0;done=true}else if(sum===7){ret=betType==='dont'?stake*2:0;done=true}else await sleep(320)}}if(ret)adjust(ret,{win:ret>stake});$('#crapsResult').innerHTML=ret>stake?`<strong class="win">WIN · return ${money(ret)}</strong>`:ret===stake?`<strong class="push">PUSH · ${money(stake)} returned</strong>`:`<strong class="loss">LOSE · ${money(stake)}</strong>`;$('#crapsPoint').textContent='COME-OUT ROLL';busy=false}}
  function bindCraps(){const b=$('#crapsLobbyCard');if(b)b.onclick=openCrapsIntegrity}
  bindCraps();new MutationObserver(bindCraps).observe(document.body,{childList:true,subtree:true});

  const priorTutorial=window.showTutorial;
  window.showTutorial=function integrityTutorial(game){
    if(game==='roulette')return showModal('<p class="kicker">HOW TO PLAY</p><h2>American Roulette</h2><p>38 pockets: 1–36, 0 and 00. The wheel carries every number in American wheel order beneath a fixed pointer. The final physical wheel angle determines the pocket under that pointer, and that visible pocket is scored.</p><div class="modal-card"><b>35:1 straight · 2:1 dozens · 1:1 even-money</b><small>Each pocket occupies exactly 1/38 of the wheel.</small></div>');
    if(game==='keno')return showModal('<p class="kicker">HOW TO PLAY</p><h2>Keno</h2><p>Choose 1–10 spots. Twenty numbers are drawn one at a time from a live remaining pool of 1–80. Each number is removed after it appears, so duplicates are impossible. Your final hit count determines the displayed payout.</p>');
    if(game==='slots')return $('#slotHowBtn')?.click();
    return priorTutorial?priorTutorial(game):undefined;
  };
})();
